export enum FormFieldType {
    TEXT = 'text',
    PASSWORD = 'password',
    EMAIL = 'email',
    NUMBER = 'number',
    CHECKBOX = 'checkbox',
    RADIO = 'radio',
    SELECT = 'select',
    SELECT_CHECKBOX = 'select_checkbox',
    TEXTAREA = 'textarea',
    FILE = 'file',
    CHOOSE_FILE = 'choose-file',
    MULTIFILE = 'multifile',
    PICK_FILE = 'pick-file',
}
